- id: '1661355840162'
  alias: Notify when backups stale
  description: ''
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.backups_stale
      from: 'off'
      to: 'on'
  condition: []
  action:
    - service: notify.notify
      data:
        title: Backups stale
        message: Your backups are not working!
  mode: single

- id: "Startup Script"
  initial_state: true
  alias: System Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: shell_command.setup
- id: '1662837841101'
  alias: Ring Keypad Automations
  description: ''
  use_blueprint:
    path: ImSorryButWho/synchronize-ring-alarm-keypad-v2-with-alarmo.yaml
    input:
      keypad: bd46734ddaacc61288e4371c1b68b832
      alarm: alarm_control_panel.alarmo
