# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: processor_temperature
      - type: memory_free
      - type: disk_use
      - type: disk_use_percent
        arg: /
      - type: disk_free

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

ffmpeg:
stream:
camera:
  - platform: generic
    name: "wyzeCam1"
    stream_source: !secret wyze_cam1
    authentication: digest
    rtsp_transport: udp
  - platform: generic
    name: "wyzeCam2"
    stream_source: !secret wyze_cam2
    authentication: digest
    rtsp_transport: udp
  - platform: generic
    name: "ptz"
    stream_source: !secret amcrest_ptz
    authentication: digest
    rtsp_transport: udp
  - platform: ffmpeg
    name: "ptz_vertical"
    input: !secret amcrest_ptz
    extra_arguments: -vf "transpose=1"

amcrest:
  - host: !secret amcrest_ptz_ip
    username: !secret amcrest_username
    password: !secret amcrest_password
    stream_source: "rtsp"
    resolution: "low"

shell_command:
  setup: "/config/scripts/setup.sh > /config/setup.log"
