# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: processor_temperature
      - type: memory_free
      - type: disk_use
      - type: disk_use_percent
        arg: /
      - type: disk_free

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

stream:
camera:
  - platform: generic
    name: "cam1"
shell_command:
  setup: "/config/scripts/setup.sh > /config/setup.log"
